spring.application.name=gobeyond
spring.graphql.path=/graphql

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.endpoint=/graphql
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.locations=classpath:graphql/

spring.datasource.url=jdbc:postgresql://localhost:5432/gobeyond
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000